spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: account
        format_sql: true
    show-sql: "${SHOW_SQL:false}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:parcel}"
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
  flyway:
    enabled: true
    schemas: account
    create-schemas: true
    baseline-version: 1

server:
  port: 8001
