server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service-courier-route
          uri: ${USER_SERVICE_HOST:http://localhost:8001}
          predicates:
            - Path=/api/v1/user/courier/**
            - Method=PUT
          filters:
            - JwtAuth=COURIER

        - id: user-service-admin-route
          uri: ${USER_SERVICE_HOST:http://localhost:8001}
          predicates:
            - Path=/api/v1/user/courier/**
          filters:
            - JwtAuth=ADMIN

        - id: auth-public-route
          uri: ${AUTH_SERVICE_HOST:http://localhost:8002}
          predicates:
            - Path=/api/public/v1/auth/**

        - id: auth-admin-route
          uri: ${AUTH_SERVICE_HOST:http://localhost:8002}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuth=ADMIN

        - id: order-client-route
          uri: ${ORDER_SERVICE_HOST:http://localhost:8003}
          predicates:
            - Path=/api/v1/order/client/**
          filters:
            - JwtAuth=CLIENT

        - id: order-admin-route
          uri: ${ORDER_SERVICE_HOST:http://localhost:8003}
          predicates:
            - Path=/api/v1/order/admin/**
          filters:
            - JwtAuth=ADMIN

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.github.chmatvey.apigateway.filter: DEBUG
