server:
  port: 8003

spring:
  application:
    name: order-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: parcel
        format_sql: true
    show-sql: "${SHOW_SQL:false}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orderdb}"
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
  flyway:
    enabled: true
    schemas: parcel
    create-schemas: true
    baseline-version: 1

integration:
  delivery:
    url: ${DELIVERY_SERVICE_URL:http://localhost:8004/api/internal/v1/delivery}
