server:
  port: 8004

spring:
  application:
    name: delivery-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: parcel
        format_sql: true
    show-sql: "${SHOW_SQL:false}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deliverydb}"
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
  flyway:
    enabled: true
    schemas: parcel
    create-schemas: true
    baseline-version: 1
  rabbitmq:
    template:
      exchange: ${ORDER_ASSIGN_EXCHANGE:parcel.direct}
    addresses: ${RABBITMQ_HOST:localhost:5672}

integration:
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8003/api/internal/v1/order}

message-broker:
  queues:
    order-assign: ${ORDER_ASSIGN_QUEUE:order-assign.queue}
  routing-keys:
    delivery-accept: ${DELIVERY_ASSIGN_ROUTING_KEY:delivery-accept.routing-key}
    delivery-complete: ${DELIVERY_COMPLETE_ROUTING_KEY:delivery-complete.routing-key}