server:
  port: 8002

spring:
  application:
    name: auth-service

integration:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8001/api/internal/v1/user}

password:
  salt: ${PASSWORD_SALT:farel}

jwt:
    secret: ${JWT_SECRET:farel}
    expiration: 3600