spring:
  application:
    name: auth-service

server:
  port: 8002

integration:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8001/api/internal/v1/user}

password:
  salt: farel

jwt:
    secret: farel
    expiration: 3600